// Contract Addresses
export const PAYROLL_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_PAYROLL_CONTRACT_ADDRESS;
export const MOCK_USDC_ADDRESS = process.env.NEXT_PUBLIC_MOCK_USDC_ADDRESS;
export const ESOP_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_ESOP_CONTRACT_ADDRESS;
